### PR TITLE
import of existing modules

### PR DESCRIPTION
**Pull request by mambax7**
If you have old modules that you would like to refresh using ModuleBuilder, you can now save time by importing them:
1) The old module has to be installed and active
2) In the Admin's Modules view, click on the "Import Module button"

image

3) Select the module that you would like to import, and set the name (it could be the same, or it could be different)

image

4) Click on the "Import" button, and ModuleBuilder will import the database structure.

image

5) Now you can make changes to the tables and fields, and once satisfied, you can re-build the module, but with the latest XOOPS technologies! :)

### CODE REVIEW

**Comment by ggoffy** [comment]
wow, great, I will check it this weekend :)

**Comment by mambax7** [comment]
Make sure you change the size of "mod_version" in the modulebuilder_modules" table from 4 to 10:
image

I'll have to add it to the update routine....

**Comment by ggoffy** [comment]
I have tested and found basically no errors

https://github.com/mambax7/modulebuilder/pull/1
I have added a result handling and added all to the templates

**Comment by ggoffy** [comment]
@mambax7 
should I merge or do you want to wait for comments of geekwright and zyspec?

**Comment by mambax7** [comment]
Go ahead and merge! 
Thanks!

**Pull request merged**
